confluence:
    image: translucent/atlassian-plugin-sdk:latest
    volumes:
      - ./atlassian/app:/usr/src/app
      - ./atlassian/repository:/root/.m2/repository/
    expose:
        - 1990
    dns: 192.168.99.1
    environment:
        VIRTUAL_HOST: atlassian-confluence.dev

    command: atlas-run-standalone --container tomcat7x --product confluence --version 6.0.0-OD-2016.13.3-1129 --data-version 6.0.0-OD-2016.13.3-1129 --bundled-plugins com.atlassian.bundles:json-schema-validator-atlassian-bundle:1.0.4,com.atlassian.upm:atlassian-universal-plugin-manager-plugin:2.21-D20160128T024330,com.atlassian.jwt:jwt-plugin:1.5.9-0019,com.atlassian.plugins:atlassian-connect-plugin:1.1.84 --jvmargs -Datlassian.upm.on.demand=true
    tty: yes


application:
    image: debian:jessie
    volumes:
        - .:/var/www/atlconnect

nginx:
    image: he8us/nginx
    ports:
        - 80

    dns: 192.168.99.1
    environment:
        VIRTUAL_HOST: atlassian-connect.dev
        DOCUMENT_ROOT: /var/www/atlconnect
        LOG_FILE: atlconnect

    links:
        - php
        - confluence

    volumes_from:
        - application

php:
    image: he8us/php-fpm-prod
    expose:
        - 9000

    links:
        - confluence

    dns: 192.168.99.1
    environment:
        APPLICATION_ENV: dev
        TIMEZONE: "Europe/Brussels"
    volumes_from:
        - application
